### PR TITLE
Added support for KModel v5

### PR DESCRIPTION
**Pull request by cscribano**
* Implemented support for nncase >=1.0
* nncase runtime 1.8.0
* Support for KModels v5

### CODE REVIEW

**Comment by starstar222** [comment]
Good work! Thank you for your contribution. 
For KModel v5 support, I suggest making it a configuration item, and disable for default, because it needs 0.7M or more memory.
In addition, I have some doubts about nncase_ V1, why not use source code but static library.

**Comment by cscribano** [comment]
Thank you for the interesting in my contribution.
* I agree that making support for kModelV5 a configurable item will be more convenient, unfortunately I currently lack the time to spare for this improvement
* As for the usage of the usage of the static library I think that this make easier to update to newest commits of nncase, compiling the v1 version requires a lot of external dependencies. Linking the stqatic libraries is the way is done in the provided SDK examples from kendryte.

**Comment by starstar222** [comment]
OK, I will making it a configuration item. If convenient, can you provide your test case about kmodel-v5

**Review by starstar222 — APPROVED** [review]

**Review by starstar222 — APPROVED** [review]

**Comment by starstar222** [comment]
I'm so sorry to tell you, the checks not completed for build firmware,  you need to put the static library in the sdk directory and resubmit another PR.

**Comment by cscribano** [comment]
Unfortunately, the static libraries are too heavy to be added to the git repository and git LFS cannot be enabled on a fork.
The only way is to download the libnncase from an external source. I will investigate if this can be done automatically at build time.

**Comment by starstar222** [comment]
You can add download scripts for nncase static libraries in file `.github/workflows/build-release-test.yml`

**Comment by kendryte747** [comment]
Here(#31) we have add support for kmodel v5, and because i have rewrite the kpu module, so i will close this pr for it is outdated.

**Pull request closed without merging**
